Update patch to use unsed var instead of void
It was triggering an error:

    config.h:90:7: error: initialization of ‘const char * (*)(const char *)’ from incompatible pointer type ‘const char * (*)(void)’ [-Wincompatible-pointer-types]
       90 |     { alsa_master_vol,      ",{\"name\":\"time\",\"full_text\":\"♪ %s\",\"color\":\"#bd93f9\"}",        NULL },
          |       ^~~~~~~~~~~~~~~